### ISSUE TITLE
Crash. Villagers?

### ISSUE THREAD

**Issue by DcNdrew** [PandaDap2006/Pandas-Extra-Details#32]
[crash-2024-01-05_21.58.18-client.txt](https://github.com/PandaDap2006/Pandas-Extra-Details/files/13848190/crash-2024-01-05_21.58.18-client.txt)

A village was going to be loaded and the game crashed multiple times. When I disabled the Details mod, the map could load. There were a bunch of baby villagers in a door. Not sure, but they can cause the problem.

**Comment by PandaDap2006** [comment]
This might be connected to the performance issues with minecraft's rendering engine, im working on a fix.

**Comment by xR4YM0ND** [comment]
Same here - Fabric 1.20.1
```js
net.minecraft.class_148: Encountered exception while building chunk meshes
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:168) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:135) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "me.pandamods.pandalib.client.render.block.ClientBlock.setBlockState(net.minecraft.class_2680)" because "block" is null
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.handler$dmd000$extra_details$execute(ChunkBuilderMeshingTask.java:569) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:112) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	... 4 more
```
https://gist.github.com/xR4YM0ND/e4f5c43f6e793e941393cad314d10282

**Comment by jmadarg** [comment]
Not sure if this one is related, but it's a similar crash
https://mclo.gs/uzy4LcZ
```
Description: Encountered exception while building chunk meshes
java.lang.NullPointerException: Cannot invoke "java.util.Set.stream()" because the return value of "me.pandamods.pandalib.impl.CompileResultsExtension.getBlocks()" is null

```
