### ISSUE TITLE
[1.20.1] Crash for some reason

### ISSUE THREAD

**Issue by Katranune** [PandaDap2006/Pandas-Extra-Details#38]
log is very short and indescriptive but im pretty sure it's this mod
[latest.log](https://github.com/PandaDap2006/Pandas-Extra-Details/files/14899157/latest.log)

debug.log just in case
[debug.log](https://github.com/PandaDap2006/Pandas-Extra-Details/files/14899158/debug.log)

**Comment by Katranune** [comment]
the reason i think it's this mod is because prism launcher has a little bit of extra text that isnt in the log for whatever reason
`Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.module.ResolutionException: Modules pandalib and extra_details export package me.pandamods.pandalib to module impactfulweather
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Exiting with ERROR
Process exited with code 2.`

**Comment by Katranune** [comment]
the ```"Caused by: java.lang.module.ResolutionException: Modules pandalib and extra_details export package me.pandamods.pandalib to module impactfulweather"``` line is a different mod each time

**Comment by Katranune** [comment]
probably an issue with how notoriously bad forge is with mixins because it works perfectly fine on fabric with the mods it has issues with on forge

**Comment by PandaDap2006** [comment]
Sorry about the late response, could you check if there is 2 cloth config jars, from what i can see it looks like its trying to load 2 jars with the same modid.

**Comment by Katranune** [comment]
that probably was been the issue, i redid everything and even with the same mods, its not crashing. (it does not have 2 cloth configs, i was also using sinytra so its very possible a fabric mod needed cloth config)
