### ISSUE TITLE
crash on loading in world/server

### ISSUE THREAD

**Issue by Atticuss26** [PandaDap2006/Pandas-Extra-Details#46]
[16:10:36] [Chunk Render Task Executor #0/ERROR]: Chunk build failed
org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in me/jellysquid/mods/sodium/client/render/chunk/compile/tasks/ChunkBuilderMeshingTask::execute(Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildContext;Lme/jellysquid/mods/sodium/client/util/task/CancellationToken;)Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildOutput; has incompatible changes at opcode 150 in callback extra_details-common.mixins.json:client.sodium.ChunkBuilderMeshingTaskMixin from mod extra_details->@Inject::execute(Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildContext;Lme/jellysquid/mods/sodium/client/util/task/CancellationToken;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lme/jellysquid/mods/sodium/client/render/chunk/data/BuiltSectionInfo$Builder;Lnet/minecraft/class_852;Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildBuffers;Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderCache;Lme/jellysquid/mods/sodium/client/world/WorldSlice;IIIIIILnet/minecraft/class_2338$class_2339;Lnet/minecraft/class_2338$class_2339;Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderContext;IIILnet/minecraft/class_2680;Lnet/minecraft/class_3610;)V.
 Expected: [Lme/jellysquid/mods/sodium/client/render/chunk/data/BuiltSectionInfo$Builder;, Lnet/minecraft/class_852;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildBuffers;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderCache;, Lme/jellysquid/mods/sodium/client/world/WorldSlice;, I, I, I, I, I, I, Lnet/minecraft/class_2338$class_2339;, Lnet/minecraft/class_2338$class_2339;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderContext;, I, I, I, Lnet/minecraft/class_2680;, Lnet/minecraft/class_3610;]
    Found: [Lme/jellysquid/mods/sodium/client/render/chunk/data/BuiltSectionInfo$Builder;, Lnet/minecraft/class_852;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildBuffers;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderCache;, Lme/jellysquid/mods/sodium/client/world/WorldSlice;, I, I, I, I, I, I, Lnet/minecraft/class_2338$class_2339;, Lnet/minecraft/class_2338$class_2339;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderContext;, I, I, I, Lnet/minecraft/class_2680;]
Available: [Lme/jellysquid/mods/sodium/client/render/chunk/data/BuiltSectionInfo$Builder;, Lnet/minecraft/class_852;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildBuffers;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderCache;, Lme/jellysquid/mods/sodium/client/world/WorldSlice;, I, I, I, I, I, I, Lnet/minecraft/class_2338$class_2339;, Lnet/minecraft/class_2338$class_2339;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderContext;, I, I, I, Lnet/minecraft/class_2680;]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.handler$cdj000$extra_details$execute$missing(ChunkBuilderMeshingTask.java) ~[sodium-fabric-0.5.8+mc1.20.4.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:88) ~[sodium-fabric-0.5.8+mc1.20.4.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39) ~[sodium-fabric-0.5.8+mc1.20.4.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[sodium-fabric-0.5.8+mc1.20.4.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[sodium-fabric-0.5.8+mc1.20.4.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:10:37] [Render thread/ERROR]: Unreported exception thrown!
java.lang.RuntimeException: Exception thrown while executing job
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobResult.unwrap(ChunkJobResult.java:27) ~[sodium-fabric-0.5.8+mc1.20.4.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.collectChunkBuildResults(RenderSectionManager.java:347) ~[sodium-fabric-0.5.8+mc1.20.4.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.uploadChunks(RenderSectionManager.java:280) ~[sodium-fabric-0.5.8+mc1.20.4.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:191) ~[sodium-fabric-0.5.8+mc1.20.4.jar:?]
	at net.minecraft.class_761.method_3273(class_761.java:21267) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1020) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1098) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:866) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1327) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in me/jellysquid/mods/sodium/client/render/chunk/compile/tasks/ChunkBuilderMeshingTask::execute(Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildContext;Lme/jellysquid/mods/sodium/client/util/task/CancellationToken;)Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildOutput; has incompatible changes at opcode 150 in callback extra_details-common.mixins.json:client.sodium.ChunkBuilderMeshingTaskMixin from mod extra_details->@Inject::execute(Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildContext;Lme/jellysquid/mods/sodium/client/util/task/CancellationToken;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lme/jellysquid/mods/sodium/client/render/chunk/data/BuiltSectionInfo$Builder;Lnet/minecraft/class_852;Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildBuffers;Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderCache;Lme/jellysquid/mods/sodium/client/world/WorldSlice;IIIIIILnet/minecraft/class_2338$class_2339;Lnet/minecraft/class_2338$class_2339;Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderContext;IIILnet/minecraft/class_2680;Lnet/minecraft/class_3610;)V.
 Expected: [Lme/jellysquid/mods/sodium/client/render/chunk/data/BuiltSectionInfo$Builder;, Lnet/minecraft/class_852;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildBuffers;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderCache;, Lme/jellysquid/mods/sodium/client/world/WorldSlice;, I, I, I, I, I, I, Lnet/minecraft/class_2338$class_2339;, Lnet/minecraft/class_2338$class_2339;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderContext;, I, I, I, Lnet/minecraft/class_2680;, Lnet/minecraft/class_3610;]
    Found: [Lme/jellysquid/mods/sodium/client/render/chunk/data/BuiltSectionInfo$Builder;, Lnet/minecraft/class_852;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildBuffers;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderCache;, Lme/jellysquid/mods/sodium/client/world/WorldSlice;, I, I, I, I, I, I, Lnet/minecraft/class_2338$class_2339;, Lnet/minecraft/class_2338$class_2339;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderContext;, I, I, I, Lnet/minecraft/class_2680;]
Available: [Lme/jellysquid/mods/sodium/client/render/chunk/data/BuiltSectionInfo$Builder;, Lnet/minecraft/class_852;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildBuffers;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderCache;, Lme/jellysquid/mods/sodium/client/world/WorldSlice;, I, I, I, I, I, I, Lnet/minecraft/class_2338$class_2339;, Lnet/minecraft/class_2338$class_2339;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderContext;, I, I, I, Lnet/minecraft/class_2680;]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.handler$cdj000$extra_details$execute$missing(ChunkBuilderMeshingTask.java) ~[sodium-fabric-0.5.8+mc1.20.4.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:88) ~[sodium-fabric-0.5.8+mc1.20.4.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39) ~[sodium-fabric-0.5.8+mc1.20.4.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[sodium-fabric-0.5.8+mc1.20.4.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[sodium-fabric-0.5.8+mc1.20.4.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:10:37] [Render thread/WARN]: [SeamlessLoadingScreen] Fade screen has been skipped due to someone replacing the screen before we could add our own after DownloadingTerrainScreen
[16:10:37] [Render thread/INFO]: [ChatLog.serialize] Saved the chat log containing 5 messages and 0 sent messages to 'C:\Users\attic\AppData\Roaming\PrismLauncher\instances\Fabulously.Optimized-5.8.0-beta.10\.minecraft\logs\chatlog.json'
[16:10:37] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalArgumentException: duplicate event invoker for type interface fuzs.puzzleslib.api.event.v1.server.TagsUpdatedCallback
	at fuzs.puzzleslib.impl.event.core.EventInvokerImpl.register(EventInvokerImpl.java:74) ~[PuzzlesLib-v20.4.42-1.20.4-Fabric.jar:?]
	at fuzs.puzzleslib.fabric.impl.event.FabricEventInvokerRegistryImpl.register(FabricEventInvokerRegistryImpl.java:430) ~[PuzzlesLib-v20.4.42-1.20.4-Fabric.jar:?]
	at fuzs.puzzleslib.fabric.api.event.v1.core.FabricEventInvokerRegistry.register(FabricEventInvokerRegistry.java:59) ~[PuzzlesLib-v20.4.42-1.20.4-Fabric.jar:?]
	at fuzs.puzzleslib.fabric.api.event.v1.core.FabricEventInvokerRegistry.register(FabricEventInvokerRegistry.java:45) ~[PuzzlesLib-v20.4.42-1.20.4-Fabric.jar:?]
	at fuzs.puzzleslib.fabric.impl.event.FabricEventInvokerRegistryImpl.registerEventHandlers(FabricEventInvokerRegistryImpl.java:116) ~[PuzzlesLib-v20.4.42-1.20.4-Fabric.jar:?]
	at fuzs.puzzleslib.fabric.impl.core.FabricFactories.registerEventHandlers(FabricFactories.java:65) ~[PuzzlesLib-v20.4.42-1.20.4-Fabric.jar:?]
	at fuzs.puzzleslib.impl.event.core.EventInvokerImpl.initialize(EventInvokerImpl.java:35) ~[PuzzlesLib-v20.4.42-1.20.4-Fabric.jar:?]
	at fuzs.puzzleslib.fabric.impl.client.event.FabricClientEventInvokers.lambda$registerLoadingHandlers$1(FabricClientEventInvokers.java:90) ~[PuzzlesLib-v20.4.42-1.20.4-Fabric.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35) ~[fabric-lifecycle-events-v1-2.3.1+a67ffb5d4f-78d2a96fc756e69a.jar:?]
	at net.minecraft.class_310.handler$cjg000$fabric-lifecycle-events-v1$onStart(class_310.java:16288) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:870) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.modify$gob000$vanillafix$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:39801) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:911) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]

**Comment by PandaDap2006** [comment]
Will be fixed in next release

**Comment by Babagi75** [comment]
Can't wait
